### PR TITLE
Use FontAwesome5 syntax

### PR DESCRIPTION
**Pull request by felipecalvo**
## :dart: Goal

Use FontAwesome5 syntax as well as change some icons.

## :spiral_notepad: Notes

The biggest change on FA5 is that instead of having solid and outlined icons with different `fa-` prefixes (such as `fa-user` and `fa-user-o`), the style is now dictated by `fas` (s for solid), `far` (r for regular) and `fab` (b for brand). Therefore, `fas fa-user` shows a solid user icon, `far fa-user` shows the outlined style, and `fab fa-twitter` is the style for brand icons.

Minor changes in this PR include updating the names to match their new FA5 styles. For example, FA4's `fa-facebook` was moved to `fa-facebook-f` on FA5, while the new `fa-facebook` is a different icon altogether.

Every major change is up for discussion on the following comments. :+1: if they're okay.

### CODE REVIEW

**Comment by felipecalvo** [comment]
## Fullscreen mode

I replaced the fullscreen mode icons with more standard expand/compress variants, such as the ones found on YouTube. However, I later noticed that Gmail does use the old style for email composing. I'm fine with either - the main reason I changed it is the stacked icons (fullscreen arrows + square outline) was causing a misalignment.

image
image

**Comment by felipecalvo** [comment]
## Left-facing editor tooltips
The topmost tooltip cannot currently be seen on fullscreen mode, as it appears off-screen.

image
image

**Comment by felipecalvo** [comment]
## Solid user icon

This change is also motivated by code simplicity. As we're using solid icons by default, we'd need to make an exception just for the user icon, which is regular (outlined).

However, it makes no sense from a design point of view to have a single outlined icon while all the others are solid.
image

**Comment by felipecalvo** [comment]
## Logout icon
Add a logout icon.
image

**Comment by felipecalvo** [comment]
## Indent on multiple files editor

Probably an oversight, as I added and it works as intended from what I tested. The reset button is commented, though.
https://github.com/mumuki/mumuki-laboratory/blob/f41f508b90af446dd18a4d2884946322a77f726b/app/views/layouts/exercise_inputs/editors/_multiple_files.html.erb#L36
image
image

**Review by luchotc — APPROVED** [review]
I've used :+1: for the ones that are OK IMO and :heart: for the ones that I loved.
Spoiler alert: I ended up using :heart: in all of them :100: 

There seems to be an issue with mumuki-styles though

**Comment by felipecalvo** [comment]
Yes, I'm checking that out, thanks.

**Comment by felipecalvo** [comment]
I can't quite figure it out, but I think we just can't point to a particular ref or branch (in contrast to a tag) due to all the work done when a version is released.

I went as far back as checking out this commit ec8fa16a and manually pointing to its corresponding styles ref (https://github.com/mumuki/mumuki-styles/commit/a7e6f1d65722247989f50c52f56ffd1ed2167d7f) and the same error occurs.

I'm fairly sure the checks failed on Travis as well until we used a new tag. I'm tempted to 2.0 mumuki-styles, point to it and see if it's fixed...

**Comment by luchotc** [comment]
It's ok! We are ignoring everything inside app/ so we can't manually check it out, as styles github repo doesn't really have that gem.
Let's deploy styles (it should be a major, I forgot to add that in it's PR) and then point it from here properly.

**Pull request merged**
