### PR TITLE
Redirecting only if the user is student of the invitation's course - Fixes mumuki/mumuki-classroom-api#163

### PR DESCRIPTION
**Pull request by rodri042**
Fixes https://github.com/mumuki/mumuki-classroom-api/issues/163

### CODE REVIEW

**Comment by flbulgarelli** [comment]
Hmm, are we sure this fixes the issue? 

It looks that what @rgonzalezt reported is an improper assignation, not just a broken redirection.

**Comment by rodri042** [comment]
@flbulgarelli I think the problem was that if the students are already registered in a course of the same organization, this redirect prevents them from joining and adding the right permission (and sending the notification to classroom)

**Comment by flbulgarelli** [comment]
OK, sound good. Could you write a `feature_test` for it, please? I think there are not tests like those for the invitation flow, but you can use any of the `*_flow_spec` as inspiration. E.g. https://github.com/mumuki/mumuki-laboratory/blob/master/spec/features/guides_flow_spec.rb

**Comment by rodri042** [comment]
@flbulgarelli test added!

**Pull request merged**
