### PR TITLE
Remove second default content from response

### LINKED ISSUE #1057: Interpolations in default code should work with blocks

### PR DESCRIPTION
**Pull request by julian-berbel**
Fixes #1057.

Should be deployed after mumuki/mumuki-gobstones-runner#106.

### CODE REVIEW

**Comment by flbulgarelli** [comment]
Won't this break the reset button?

**Comment by julian-berbel** [comment]
Well, by itself, yes (Only Gobstones' though).

As explained in https://github.com/mumuki/mumuki-laboratory/issues/1057#issuecomment-390250986, when entering an exercise, the response HTML from laboratory has the exercise's default content twice, placed in hidden fields (default_content and mu-custom-editor-default-value).

We are currently using the default_content field everywhere except on the Gobstones runner.

To avoid anything breaking we need to deploy mumuki/mumuki-gobstones-runner#106 before this. I should have pointed that out before, my bad!

**Comment by julian-berbel** [comment]
Well, by itself, yes.

As explained in #1057, when entering an exercise, the response HTML from laboratory has the exercise’s default content twice, placed In hidden fields. 

This PR is removing the second unnecessary content

**Comment by luchotc** [comment]
LGTM as it's not necessary to deploy both changes at the same time. We can deploy Gobstones by itself and then remove the unnecessary default-content in the editor extra layout.
In this case, the default-content is being exposed for both internal and external use. Should we prefix it with mu as well?

**Pull request merged**
