### PR TITLE
improving kids results in bubble

### LINKED ISSUE #1126: No se ve la expectativa en KIDS en dispositivos moviles
screenshot_20180725-122122

### PR DESCRIPTION
**Pull request by luchotc**
Resolves #1126 

Quoting fran: @fedescarpa please review and merge

### CODE REVIEW

**Comment by flbulgarelli** [comment]
Could you provide screenshots?

**Comment by luchotc** [comment]
grande
media
mini

**Comment by luchotc** [comment]
Although this is an improvement, we should add arrows for navigating the bubble. But that's for another issue :smile:

**Comment by luchotc** [comment]
@fedescarpa Thoughts?

**Comment by fedescarpa** [comment]
Awesome

**Pull request merged**
