### PR TITLE
Feature user avatars

### PR DESCRIPTION
**Pull request by felipecalvo**
Missing:
- Domain tag, once merged at https://github.com/mumuki/mumuki-domain/pull/84
- ~~Seed a couple open-source avatars~~

### CODE REVIEW

**Comment by luchotc** [comment]
@felipecalvo Could we undraft this one or something else is missing?

**Comment by luchotc** [comment]
Resolves #1404

**Comment by flbulgarelli** [comment]
I have just rebased this PR and update domain references. Can we already merge it?

**Comment by felipecalvo** [comment]
Yes, as soon as I get a :+1: at https://github.com/mumuki/mumuki-domain/pull/91

**Pull request merged**
