### PR TITLE
Unifying ACE and Markdown themes

### PR DESCRIPTION
**Pull request by flbulgarelli**
image
image

## JavaScript

image
image

image
image

image
image
image

### CODE REVIEW

**Comment by flbulgarelli** [comment]
### Prolog

image

**Comment by flbulgarelli** [comment]
## QSIM

image
image

**Comment by flbulgarelli** [comment]
## Misc 

image

**Comment by aguspina** [comment]
LGTM

**Comment by flbulgarelli** [comment]
@faloi yes and no. I actually requested @Charlyzzz to change the lexer in order to recognize directions and colors as literals, in the same way booleans and numbers are. That will fix the problem in the Markdown side.

In the ACE side, the problem is that the Gobstones ACE component is not parsing them properly and recognizes them as keywords. We should fix the ACE component, but that is a different story.

**Comment by faloi** [comment]
Ok. Regarding the ACE issue, isn't it already solved? If not, how does it
work in gbs web?

**Comment by flbulgarelli** [comment]
> Ok. Regarding the ACE issue, isn't it already solved? If not, how does it work in gbs web?

I really don't know. Perhaps Gobstones Web is using a modified version of the Gobstones ACE mode. @alvarezariel? @rodri042 ?

**Comment by faloi** [comment]
One more thing: `MOV R5, 0120` is not valid QSim, the `0x` prefix is mandatory for hex literals (and the error that arises if you miss it is really awful). Any chance we don't colorize it or are we just using a standard assembly highlighter?

**Comment by flbulgarelli** [comment]
> One more thing: MOV R5, 0120 is not valid QSim, the 0x prefix is mandatory for hex literals (and the error that arises if you miss it is really awful). Any chance we don't colorize it or are we just using a standard assembly highlighter?

See my comments here https://github.com/mumuki/mumuki-qsim-runner/issues/11 and add yours. It is not a theme issue, it is a lexer issue.

**Pull request merged**
