### PR TITLE
improving arrow behaviour in kids bubble

### LINKED ISSUE #1164: No aparecen las flechas para bajar el texto de la consigna
@fedescarpa 

No están las flechas para subir o bajar el texto que no entra completo en el globo de la consigna/ayuda.

image

### PR DESCRIPTION
**Pull request by luchotc**
Resolves #1164 

With the current approach it was very difficult to improve the bubble, so i change the way it's done. I collapsed all the paragraphs together ( we could keep them separate, but @NadiaFinzi told me that she prefers to enter the text without paragraphs), and the arrows are simply a way to scroll  the text easily. This also allows us to change the behavior for desktop users (although i think we shouldn't, for consistency), as we could use the normal scrollbar for desktop and keep the arrows for mobile.

I didn't provide a screenshot cuz the final look is the same. If you want to, i'll make a video :smile:

### CODE REVIEW

**Comment by flbulgarelli** [comment]
Looks good to me

**Comment by luchotc** [comment]
@fedescarpa Thoughts? 
On the other hand, any idea why bootstrap-mincer is failing in the build? :thinking:

**Comment by flbulgarelli** [comment]
Is working locally? Perhaps we should move to a more specific version of Styles and the other Bootstrap gems

**Comment by flbulgarelli** [comment]
> It looks like the problem is with mumuki-styles, changing from 1.17 to 1.18. This is bad, any idea about what has changed?

The only change is the migration from bower to webpack :confused: @Javi could you check those errors and ensure that `mumuki-styles > 1.18` can work with laboratory?

**Comment by Javi** [comment]
The error goes away on my end with ``mumuki-styles`` updated to ``1.18.2``, which removes the broken scss file

**Pull request merged**
