### PR TITLE
Feature progressive display

### PR DESCRIPTION
**Pull request by flbulgarelli**
# :dart: Goal

This PR shows chapters progressively, by completing previous chapters. 

# :camera: Screenshots

Without progressive display: 

image

With progressive display: 

image

# :thinking: Doubts

~I think it can be misleading to find less chapters than expected. Why don't we display a message that states _there are still X more chapters. Complete previous chapters to unlock them_. What do you think?~ See next comments and https://github.com/mumuki/mumuki-laboratory/pull/1410#issuecomment-643462843

~Also, @luchotc and @felipecalvo, since behavior is completly indicators-based - yay :confetti_ball:  - I still don't understand what will happen when user has _mostly_ completed the previous chapters. Will still be considered incomplete? It would be nice to have some tolerance level here.~ See https://github.com/mumuki/mumuki-domain/pull/96

# :soon: Future work

~We could alternatively display chapters grayed, this way:~

image

~However I am not convinced of this change as it is not clear what is happening. As a first iteration of the progressive display feature, I'd rather keep this as-is.  I am leaving that code here: https://github.com/mumuki/mumuki-laboratory/tree/feature-disabled-progressive-display~ See next comments and https://github.com/mumuki/mumuki-laboratory/pull/1410#issuecomment-643462843

# :back: Backward compatibility 

This is a new feature and requires a minor version, but no backward incompatible changes have been introduced. If you don't send  `enable_progressive_display!` to an organization, nothing will change. 

# :eyes: See also

* Related to https://github.com/mumuki/mumuki-domain/pull/95
* Related to https://github.com/mumuki/mumuki-domain/pull/96

### CODE REVIEW

**Comment by luchotc** [comment]
I'll review the code thoroughly tomorrow.

I like how it looks grayed. Nevertheless, I think that it isn't enough and we should have some kind of lock beside it to make it more explicit (and more daltonic friendly).
This proposal may be too coupled to this layout, but maybe we could just list the title and replace the description for some text saying that it isn't available yet as they have to complete the previous chapter.

Regarding of your inquiry with the indicators, there are two main things that we can ask to them: `completed?` and `completion_percentage?`. Using the latter we could implement some kind of tolerance. (Remember that nowadays the hierarchy is still book -> topics -> guides -> exercises indicator-wise, but we are moving to another schema: https://app.diagrams.net/#G1uY2YTUYyVgMVusgZ_h0HO0sVKu7i-EuM which will make this tolerance more meaningful)

**Comment by felipecalvo** [comment]
The greyed out version looks :fire: to me.

Still, we could show a little :lock: - I liked that suggestion - next to the chapter number or something. Even a :unlock: next to the available ones as well to make it more clear. And when hovering over the lock, we could show a tooltip with an appropiate message. How about it?

There wouldn't be any (unlocked) locks on organizations without progressive display enabled, as they don't add any kind of meaningful information.

**Comment by felipecalvo** [comment]
Or maybe something like this? I actually like how it turned out.

image

**Comment by flbulgarelli** [comment]
Updated screenshot: 
image

**Pull request merged**
